version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=trafego
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=rm99266
      - SPRING_DATASOURCE_PASSWORD=160596
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_SECURITY_USER_NAME=willian
      - SPRING_SECURITY_USER_PASSWORD=123

  test:
    build:
      context: .
      dockerfile: Dockerfile
