name: Checkout Codec

on:
  push:
    branches:
      - feature/action-01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: ./mvnw test
