name: Continuous Delivery to Azure

on:
  push:
    branches:
      - develop  # A branch que você deseja monitorar para implantações

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Senha do Docker Hub

      - name: Build Docker image
        run: |
          docker build -t luanuink/fiap_gereciamento_de_trafico_api:latest .  # Altere 'myapp' para o nome da sua imagem

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fiap-gerenciamento-de-trafico-api  # Nome do seu aplicativo no Azure
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Segredo que contém o perfil de publicação
          images: luanuink/fiap_gereciamento_de_trafico_api:latest  # Imagem que você acabou de publicar
